#!/usr/bin/bash

set -e

cd /data
rm -rf openpilot
time git clone https://github.com/BogGyver/openpilot.git -b tesla_unity_beta --recurse-submodules --depth 1

cd /data/data/com.termux/files
echo $'#!/usr/bin/bash\n\ncd /data/openpilot\n./launch_openpilot.sh\n' > continue.sh
chmod +x continue.sh
echo "Install complete, rebooting..."
reboot
